### ISSUE TITLE
Register fix using pattern + required 

### ISSUE THREAD

**Issue by kitare17** [Midoraa/Final-Project-PRJ301-PetShop#3]
``

**Comment by kitare17** [comment]
<form action="" method="get">
    Username <input type="text" minlength="7" maxlength="50" required pattern="[a-zA-Z0-9]+"> 
    <br>
    Password <input type="password" minlength="7" maxlength="50" required pattern="[a-zA-Z0-9]+">
    <br>
    Comfirm password <input type="password" minlength="7" maxlength="50" required pattern="[a-zA-Z0-9]+"> 
    <br>
    
    Email <input type="email" required>
    <br>
    Phone <input type="tel" maxlength="10" minlength="10" required pattern="[0-9]{10}"> 
    <br>
    <input type="submit">
  </form>

**Comment by kitare17** [comment]
Username <input type="text" minlength="7" maxlength="50" required pattern="[a-zA-Z0-9]+"> 
    <br>
    Password <input type="password" minlength="7" maxlength="50" required pattern="[a-zA-Z0-9]+">
    <br>
    Comfirm password <input type="password" minlength="7" maxlength="50" required pattern="[a-zA-Z0-9]+"> 
    <br>

**Comment by IceVision076** [comment]
ông im mẹ mồm đi
